In [43]:
%matplotlib inline
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import numpy.random as rng
import math
np.set_printoptions(precision = 2)

## run Gibbs sampling on something simple


In [97]:
def f(x): # this is our "machine" taking x --> p(x), but un-normalised.
    energy = (2*x[0]-1)*(2*x[1]-1)*0.8
    if x[1]==0: energy += x[2]-.7
    else: energy += -2*x[2]+.4
    px = math.exp(energy)
    return(px)

def P1(Ptilde):
#     print("*" *40)
#     print(Ptilde)
    logRatio = math.log(Ptilde[1]/Ptilde[0]) # sigmoid...
    print((1.0/(1+math.exp(logRatio))) )

    return(1.0/(1+math.exp(logRatio)))   # as per first part of ex.



# print(Pmachine(x))

In [98]:
# x = np.array([1,1,0])

Ptilde = np.zeros(2)
for i in range(8):
    print("*" *40)
    # pick a dimension to reset
    j = rng.randint(3)
    print(" j :", j)
    # pick a new value, conditioning on the other dimensions
    # first, we find the two probabilities (not necessarily normalised ones)
    x[j]=0; Ptilde[0]=f(x);
    x[j]=1; Ptilde[1]=f(x);
    # then we choose a replacement value
    temp =P1(Ptilde)
    print(rng.random() < temp)
    x[j] = 1*(rng.random() < temp)

    print(x)

****************************************
 j : 0
0.16798161486607546
True
[0 1 0]
****************************************
 j : 2
0.8807970779778825
True
[0 1 1]
****************************************
 j : 1
0.9706877692486436
True
[0 1 1]
****************************************
 j : 2
0.8807970779778825
True
[0 1 1]
****************************************
 j : 2
0.8807970779778825
True
[0 1 0]
****************************************
 j : 2
0.8807970779778825
True
[0 1 1]
****************************************
 j : 2
0.8807970779778825
True
[0 1 1]
****************************************
 j : 0
0.16798161486607546
False
[0 1 1]


In [71]:
print(1*(True))

1
